name: core_kosmos
description: A new Flutter package project.
version: 1.1.0
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_screenutil: ^5.5.3+2
  responsive_framework: ^0.2.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: